# Generated by Django 3.2.9 on 2021-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'research_institutions',
            },
        ),
        migrations.CreateModel(
            name='ResearchRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'research_ranges',
            },
        ),
        migrations.CreateModel(
            name='ResearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'research_stages',
            },
        ),
        migrations.CreateModel(
            name='ResearchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'research_types',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('subject_number', models.PositiveIntegerField(null=True)),
                ('period', models.CharField(max_length=50, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researches.researchinstitution')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researches.researchrange')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='researches.researchstage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researches.researchtype')),
            ],
            options={
                'db_table': 'researches',
            },
        ),
    ]
